services: docker
before_install:
#    - sudo apt-get update
#    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker --version # for verification
    - apt-get install -y make
    - whoami
language: generic
notifications:
  slack:
    secure: Uh77/RFTPOOEbUiW/JbHo5JIrVb6ICdnLiQEHNi+ETXHGUIH93A7l47t7TUquKgrPqDT04ECY2YSxZiFUDhd/zBbqLqyKPMLn59gGe8etk+1/XvqKZg4K6Wkd9j0gSfDW/pSJGA9XsmBx9OlIMY/hJQ0Cv5gn+v8UOLwJejCTp64kKlbzdcgOeB5m7ZimLIpDLJhmxIHRXcuwhJujER0zDVoXGm2Un5cjKHnW4O1eKsaSyCg3boPH8v143gux6VE4Gpqkl2E64klDoCtYK5P5nB4F3kWb6h1+1dZh34/DdzHHXFzLFwEMHpjgobo8G9k9WeWZ0LKKavIPhZC+HdWuQQV+lacbw4oIQwKzy3xjgYvN12tUkx1vgHfejprJrbxnLIboamPpseC/SdFMQdr8lP7Q5l0ZCAfXN/GmZkzpDM8JYhxpFqek7HS1wRsabdFhKLGTeStiX4ueRLJUdizc2QnWw4dubODlDk1xdjEbiXbGrgVEL3dwguG3cKUgss+vYVQrEbqRAfePycJCBhHnjdnKFq0O01DUwbmG82WnNsno/OqPlK2BGdCYpoAQwMDXVVZmiVI/zPBYrSO7Ues9C5YUu34SARtf7gDOvPsxRzIZ6hekpTpsXdqfxHFeHviTgcUxkzs1HoAl9VQfhYIFrw/bkz9Ey65LwPnBdbP+V4=
    on_success: always
    on_failure: always
jobs:
  include:
  - stage: compile arm parts
    env:
    - DESC=ARM_CURL
    - TAG=$(grep "ENV VER_BOX" Dockerfile.pack | awk 'NF>1{print $NF}')
    - PACK_IMAGENAME=sdelrio/rpi-torrent-box
    - BUILDER_BASE=balenalib/raspberry-pi2-debian:jessie
    - GCCBUILDER_IMAGENAME=sdelrio/rpi-gccbuilder
    script:
    - echo VERSION TAG $TAG
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - make init
    - |
      if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
        echo "ARM build disabled on pull request"
      else
        docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        ./arm_curl.sh fi
      fi
  - env:
    - DESC=ARM_XMLRPC
    - TAG=$(grep "ENV VER_BOX" Dockerfile.pack | awk 'NF>1{print $NF}')
    - PACK_IMAGENAME=sdelrio/rpi-torrent-box
    - BUILDER_BASE=balenalib/raspberry-pi2-debian:jessie
    - GCCBUILDER_IMAGENAME=sdelrio/rpi-gccbuilder
    script:
    - echo VERSION TAG $TAG
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - make init
    - |
      if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
        echo "ARM build disabled on pull request"
      else
        docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        ./arm_xmlrpc.sh
      fi
  - env:
    - DESC=ARM_LIBTORRENT
    - TAG=$(grep "ENV VER_BOX" Dockerfile.pack | awk 'NF>1{print $NF}')
    - VER_LIBTORRENT=$(grep "ENV VER_LIBTORRENT" Dockerfile.pack | awk 'NF>1{print $NF}')
    - PACK_IMAGENAME=sdelrio/rpi-torrent-box
    - BUILDER_BASE=debian:jessie-slim
    - GCCBUILDER_IMAGENAME=sdelrio/rpi-gccbuilder
    script:
    - echo VERSION TAG $TAG
    - echo VER_LIBTORRENT $VER_LIBTORRENT
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - make init
    - |
      if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
        echo "ARM build disabled on pull request"
      else
        docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        ./arm_libtorrent.sh
      fi
  - stage: compile rtorrent using previous arm parts
    env:
    - DESC=ARM_RTORRENT
    - TAG=$(grep "ENV VER_BOX" Dockerfile.pack | awk 'NF>1{print $NF}')
    - VER_RTORRENT=$(grep "ENV VER_RTORRENT" Dockerfile.pack | awk 'NF>1{print $NF}')
    - VER_LIBTORRENT=$(grep "ENV VER_LIBTORRENT" Dockerfile.pack | awk 'NF>1{print $NF}')
    - CURL_VERSION=$(grep "ENV CURL_VERSION" Dockerfile.pack | awk 'NF>1{print $NF}')
    - PACK_IMAGENAME=sdelrio/rpi-torrent-box
    - BUILDER_BASE=balenalib/raspberry-pi2-debian:jessie
    - GCCBUILDER_IMAGENAME=sdelrio/rpi-gccbuilder
    script:
    - echo VERSION TAG $TAG
    - echo VER_RTORRENT $VER_RTORRENT
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker pull sdelrio/arm-curl-copy | cat
    - docker pull sdelrio/arm-xmlrpc-copy | cat
    - docker pull sdelrio/arm-libtorrent-copy | cat
    - make init && mkdir build/curl-$CURL_VERSION && mkdir build/xmlrpc-c && mkdir build/libtorrent-$VER_LIBTORRENT
    - docker run --rm -v $(pwd)/build/curl-$CURL_VERSION:/dest sdelrio/arm-curl-copy cp -a /copy/. /dest
    - docker run --rm -v $(pwd)/build/xmlrpc-c:/dest sdelrio/arm-xmlrpc-copy cp -a /copy/. /dest
    - docker run --rm -v $(pwd)/build/libtorrent-$VER_LIBTORRENT:/dest sdelrio/arm-libtorrent-copy  cp -a /copy/. /dest
    - ls $(pwd)/build
    - |
      if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
        echo "ARM build disabled on pull request"
      else
        docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        ./arm_rtorrent.sh
      fi
  - stage: build pack all docker image
    env:
    - DESC=ARM_PACK_ALL
    - TAG=$(grep "ENV VER_BOX" Dockerfile.pack | awk 'NF>1{print $NF}')
    - VER_RTORRENT=$(grep "ENV VER_RTORRENT" Dockerfile.pack | awk 'NF>1{print $NF}')
    - VER_LIBTORRENT=$(grep "ENV VER_LIBTORRENT" Dockerfile.pack | awk 'NF>1{print $NF}')
    - CURL_VERSION=$(grep "ENV CURL_VERSION" Dockerfile.pack | awk 'NF>1{print $NF}')
    - PACK_IMAGENAME=sdelrio/rpi-torrent-box
    - BUILDER_BASE=balenalib/raspberry-pi2-debian:jessie
    - GCCBUILDER_IMAGENAME=sdelrio/rpi-gccbuilder
    script:
    - echo VERSION TAG $TAG
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker pull sdelrio/arm-curl-copy | cat
    - docker pull sdelrio/arm-xmlrpc-copy | cat
    - docker pull sdelrio/arm-libtorrent-copy | cat
    - docker pull sdelrio/arm-rtorrent-copy | cat
    - make init && mkdir build/curl-$CURL_VERSION && mkdir build/xmlrpc-c && mkdir build/libtorrent-$VER_LIBTORRENT && mkdir build/rtorrent-$VER_RTORRENT
    - docker run --rm -v $(pwd)/build/curl-$CURL_VERSION:/dest sdelrio/arm-curl-copy cp -a /copy/. /dest
    - docker run --rm -v $(pwd)/build/xmlrpc-c:/dest sdelrio/arm-xmlrpc-copy cp -a /copy/. /dest
    - docker run --rm -v $(pwd)/build/libtorrent-$VER_LIBTORRENT:/dest sdelrio/arm-libtorrent-copy  cp -a /copy/. /dest
    - docker run --rm -v $(pwd)/build/rtorrent-$VER_RTORRENT:/dest sdelrio/arm-rtorrent-copy  cp -a /copy/. /dest
    - ls build
    - make BUILDER_BASE=$BUILDER_BASE PACK_IMAGENAME=$PACK_IMAGENAME pack
    - |
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        if [ "$TAG" == "master" ]; then
          docker tag $PACK_IMAGENAME:latest $PACK_IMAGENAME:$TAG
          docker push $PACK_IMAGENAME:$TAG
        else
          docker push $PACK_IMAGENAME:v$TAG
          docker push $PACK_IMAGENAME:latest
        fi
      fi
  - env:
    - DESC=x86_64_PACK_ALL
    - TAG=$(grep "ENV VER_BOX" Dockerfile.pack | awk 'NF>1{print $NF}')
    - PACK_IMAGENAME=sdelrio/rtorrent-box
    - BUILDER_BASE=debian:jessie-slim
    script:
    - echo VERSION TAG $TAG
    - make BUILDER_BASE=$BUILDER_BASE init curl xmlrpc libtorrent rtorrent pack
    - |
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        if [ "$TAG" == "master" ]; then
          docker tag $PACK_IMAGENAME:latest $PACK_IMAGENAME:$TAG
          docker push $PACK_IMAGENAME:$TAG
        else
          docker push $PACK_IMAGENAME:v$TAG
          docker push $PACK_IMAGENAME:latest
        fi
      fi

