sudo: required
services: docker
before_install:
#    - sudo apt-get update
#    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker --version # for verification
language: generic
notifications:
  slack:
    secure: Uj5nbgEuxQqGW1ScLQDLshvlEUouHLmU94v6WyKbgOg4KjJBftQS2myyr7gePTYjpHpjE6COt1+ua1fhWakidy7sZQ4a3xOoHplwG3+vWb2XUmvJ31k5gtXs8/SXwM3sCs217IPRwq78G4AvSfdcB912DQQb10oNeGeu+qpZFqN2mQZJug+X/z6J4C4ckpGEOIqpPsqhk89qpvh88RinKeHwHE9/Qb/iwTaUbyu3fzLs+IGAWpZC1ogt68Y1ZRwRrQ9BbiugtvmlNhNg71jma50DMT9GRSkz0zeLva4Ne9GMHJ1EvaAiHfu7y2ppkJwn6ddZruaMRluzY2OvXv86F0f5bMYXSd6GfRqThhDszqkEdHkxhA/hZApxJD6AaRdTwDjR+pH6ihsSapxL7aWO8Y7Nh8rkIz+63wpemUt0Y/LL+d7hNyz02L94e1AbeByqQhZizZRovrZcnifhw54X3jCjdH4TdgAhc7SYBAdh5TYMJgqKoDQBrsuDx0ap1NDFX97U90D8FWoAcWyMoUzFsMGYySzg6QGXznKsUuXlc16wJHU8wSuF3m5AGDkVsmgNF1QrdRI5S9ieCjNhaPHOoUJLZSSIpEMVeHaLkPZDc/ECrCD6bztatBWh8pMMSymRuzmRKVZwQjVFfJ61X70euoUjU1BIqEc6uwTqTl2ni04=
    on_success: always
    on_failure: always
jobs:
  include:
  - stage: build docker images
    env:
    - TAG=$(grep "ENV VERSION" Dockerfile | awk 'NF>1{print $NF}')
    - BASE_X86=debian:jessie
    - IMAGENAME_X86=sdelrio/rtorrent-box
    script:
    - echo $TAG
    - docker build --build-arg BASE_IMAGE=$BASE_X86 -t $IMAGENAME_X86 -f Dockerfile .
    - |
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        docker tag $IMAGENAME_X86 $IMAGENAME_X86:$TAG
        docker push $IMAGENAME_X86:$TAG
        docker push $IMAGENAME_X86
      fi
  - env:
    - TAG=$(grep "ENV VERSION" Dockerfile | awk 'NF>1{print $NF}')
    - BASE_ARM=resin/rpi-raspbian:jessie
    - IMAGENAME_ARM=sdelrio/rpi-torrent-box
    script:
    - echo $TAG
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker build --build-arg BASE_IMAGE=$BASE_ARM -t $IMAGENAME_ARM -f Dockerfile .
    - |
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        docker tag $IMAGENAME_ARM $IMAGENAME_ARM:$TAG
        docker push $IMAGENAME_ARM:$TAG
        docker push $IMAGENAME_ARM
      fi
