sudo: required
services: docker
before_install:
#    - sudo apt-get update
#    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker --version # for verification
    - sudo apt-get install -y make
    - whoami
language: generic
notifications:
  slack:
    secure: Uj5nbgEuxQqGW1ScLQDLshvlEUouHLmU94v6WyKbgOg4KjJBftQS2myyr7gePTYjpHpjE6COt1+ua1fhWakidy7sZQ4a3xOoHplwG3+vWb2XUmvJ31k5gtXs8/SXwM3sCs217IPRwq78G4AvSfdcB912DQQb10oNeGeu+qpZFqN2mQZJug+X/z6J4C4ckpGEOIqpPsqhk89qpvh88RinKeHwHE9/Qb/iwTaUbyu3fzLs+IGAWpZC1ogt68Y1ZRwRrQ9BbiugtvmlNhNg71jma50DMT9GRSkz0zeLva4Ne9GMHJ1EvaAiHfu7y2ppkJwn6ddZruaMRluzY2OvXv86F0f5bMYXSd6GfRqThhDszqkEdHkxhA/hZApxJD6AaRdTwDjR+pH6ihsSapxL7aWO8Y7Nh8rkIz+63wpemUt0Y/LL+d7hNyz02L94e1AbeByqQhZizZRovrZcnifhw54X3jCjdH4TdgAhc7SYBAdh5TYMJgqKoDQBrsuDx0ap1NDFX97U90D8FWoAcWyMoUzFsMGYySzg6QGXznKsUuXlc16wJHU8wSuF3m5AGDkVsmgNF1QrdRI5S9ieCjNhaPHOoUJLZSSIpEMVeHaLkPZDc/ECrCD6bztatBWh8pMMSymRuzmRKVZwQjVFfJ61X70euoUjU1BIqEc6uwTqTl2ni04=
    on_success: always
    on_failure: always
jobs:
  include:
  - stage: build x86_64 docker image
    env:
    - TAG=$(grep "ENV VER_BOX" Dockerfile.pack | awk 'NF>1{print $NF}')
    - PACK_IMAGENAME=sdelrio/rtorrent-box
    script:
    - echo VERSION TAG $TAG
    - make init curl xmlrpc libtorrent rtorrent pack
    - |
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        if [ "$TAG" == "master" ]; then
          docker push $PACK_IMAGENAME:$TAG
        else
          docker push $PACK_IMAGENAME:v$TAG
          docker push $PACK_IMAGENAME:latest
        fi
      fi
  - stage: compile arm parts
    env:
    - TAG=$(grep "ENV VER_BOX" Dockerfile.pack | awk 'NF>1{print $NF}')
    - PACK_IMAGENAME=sdelrio/rpi-torrent-box
    - BUILDER_BASE=resin/rpi-raspbian:jessie
    - GCCBUILDER_IMAGENAME=sdelrio/rpi-gccbuilder
    script:
    - '[ "${TRAVIS_PULL_REQUEST}" = "true" ] exit 0'
    - echo VERSION TAG $TAG
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    - make init
    - ./arm_curl.sh
  - env:
    - TAG=$(grep "ENV VER_BOX" Dockerfile.pack | awk 'NF>1{print $NF}')
    - PACK_IMAGENAME=sdelrio/rpi-torrent-box
    - BUILDER_BASE=resin/rpi-raspbian:jessie
    - GCCBUILDER_IMAGENAME=sdelrio/rpi-gccbuilder
    script:
    - '[ "${TRAVIS_PULL_REQUEST}" = "true" ] exit 0'
    - echo VERSION TAG $TAG
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    - make init
    - ./arm_xmlrpc.sh
  - stage: build arm docker image
    env:
    - TAG=$(grep "ENV VER_BOX" Dockerfile.pack | awk 'NF>1{print $NF}')
    - PACK_IMAGENAME=sdelrio/rpi-torrent-box
    - BUILDER_BASE=resin/rpi-raspbian:jessie
    - GCCBUILDER_IMAGENAME=sdelrio/rpi-gccbuilder
    script:
    - '[ "${TRAVIS_PULL_REQUEST}" = "true" ] exit 0'
    - echo VERSION TAG $TAG
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - docker pull sdelrio/arm-curl-copy | cat
    - docker pull sdelrio/arm-xmlrpc-copy | cat
    - make init
    - docker run --rm sdelrio/arm-curl-copy -v $(PWD)/build/curl-7.39.0:/dest cp -a /copy /dest
    - docker run --rm sdelrio/arm-xmlrpc-copy  -v $(PWD)/build/xmlrpc-c:/dest cp -a /copy /dest
    - |
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        if [ "$TAG" == "master" ]; then
          docker push $PACK_IMAGENAME:$TAG
        else
          docker push $PACK_IMAGENAME:v$TAG
          docker push $PACK_IMAGENAME:latest
        fi
      fi

